# Generated by Django 5.1.3 on 2024-12-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_payment_method_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='payment_method',
        ),
    ]
