# Generated by Django 5.1.3 on 2024-12-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_message_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('bdo', 'BDO'), ('credit-card', 'Credit Card'), ('bank-transfer', 'Bank Transfer')], default='gcash', max_length=255),
        ),
    ]
