# Generated by Django 5.1.3 on 2024-12-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
