# Generated by Django 5.1.3 on 2024-12-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=50),
        ),
    ]
