# Generated by Django 5.1.3 on 2024-12-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_remove_message_payment_method_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='payment',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
